# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        container_name: nginx-millennium
        # используем последний стабильный образ nginx
        build: ./images/nginx
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
            - ./hosts/htpasswd:/etc/nginx/htpasswd
        # nginx использует php для обработки запросов, поэтому запускается после него
        depends_on:
            - php
        networks:
            - main_network

    php:
        container_name: php-millennium
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
        networks:
            - main_network
    mysql:
        container_name: mysql-millennium
        build: ./images/mysql
        ports:
            - "3306:3306"
        volumes:
         - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
         - ./logs/mysql:/var/log/mysql
         - ./mysql-data:/var/lib/mysql
         - ./mysql-files:/var/lib/mysql-files
        # задаем пароль для root пользователя
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=millennium
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        networks:
            - main_network

    phpmyadmin:
        container_name: phpmyadmin-millennium
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - 8765:80
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        depends_on:
            - mysql
        networks:
            - main_network


networks:
    main_network:
        driver: bridge

